<div style="text-align: center;">
    <h1>Slicing/Stacking arrays, indexing with boolean arrays.</h1>
</div>

In [1]:
import numpy as np 

In [2]:
n = [6, 7, 8]
n[0:2]


[6, 7]

In [ ]:
# minus one means start minus from the index
# very last element
n[-1]

8

In [5]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [6]:
a[-1]


np.int64(8)

In [7]:
# multi dimensional array

a = np.array([[6,7,8], [1,2,3], [9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [8]:
# basic matrices. 

a[1,2]

np.int64(3)

In [9]:
a[2,2]

np.int64(2)

In [16]:
a[0:2,2]

array([8, 3])

In [17]:
a[-1]

array([9, 3, 2])

In [18]:
a[-1, 0:2]

array([9, 3])

In [19]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [21]:
a = np.array([[6, 7, 8], [1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [22]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [23]:
for column in a:
    print(column)

[6 7 8]
[1 2 3]
[9 3 2]


In [24]:
# flatten the list and print every cell
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [27]:
# stacking two arrays together

a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])