<div style="text-align: center;">
    <h1>Slicing/Stacking arrays, indexing with boolean arrays.</h1>
</div>

In [2]:
import numpy as np 

In [2]:
n = [6, 7, 8]
n[0:2]


[6, 7]

In [ ]:
# minus one means start minus from the index
# very last element
n[-1]

8

In [5]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [6]:
a[-1]


np.int64(8)

In [7]:
# multi dimensional array

a = np.array([[6,7,8], [1,2,3], [9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [8]:
# basic matrices. 

a[1,2]

np.int64(3)

In [9]:
a[2,2]

np.int64(2)

In [16]:
a[0:2,2]

array([8, 3])

In [17]:
a[-1]

array([9, 3, 2])

In [18]:
a[-1, 0:2]

array([9, 3])

In [19]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [21]:
a = np.array([[6, 7, 8], [1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [22]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [23]:
for column in a:
    print(column)

[6 7 8]
[1 2 3]
[9 3 2]


In [24]:
# flatten the list and print every cell
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [6]:
# stacking two arrays together

a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [10]:
# stack a,b together
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
# horizontal stacking
np.hstack((a,b))


array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [12]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [13]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [14]:
result = np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [16]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [17]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [22]:
# vertical split = vsplit
result = np.vsplit(a,2)
result[0]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [23]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## Indexing with boolean arrays

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
a.dtype

dtype('int64')

In [29]:
b.dtype


dtype('bool')

In [ ]:
# whenever it found True on b,
# it returned those elements. 
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [32]:
b = a > 10
b

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [33]:
a[b]

array([11])

In [34]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

NumPy arrays are pretty fast and memory efficient.