# numpy is extremely popular python module. It is heavily used in Scientific computing. 

numpy's most useful feature is n dimentional array object (a.k.a ndarry)

In [ ]:
import numpy as np
import time
import sys

l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

# difference with python list
# an numpy list. 
# numpy takes less bytes
# memory usage is less in numpy


28000
8000


In [14]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time()-start)*1000)

# numpy list
start = time.time()
result = a1+a2 
print("numpy took: ", (time.time()-start)*1000)

# this shows how fast is numpy 



python list took:  228.21378707885742
numpy took:  24.003982543945312


In [15]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a1+a2 

array([5, 7, 9])

In [16]:
a2-a1

array([3, 3, 3])

In [18]:
a1*a2 

array([ 4, 10, 18])

In [19]:
a1/a2

array([0.25, 0.4 , 0.5 ])