<div style="text-align: center;">
    <h1>NumPy: Basic array Operations</h1>
</div>

In [2]:
import numpy as np 

# 1 dimensional array
a = np.array([5,6,9])
a[0]

np.int64(5)

In [4]:
a[1]

np.int64(6)

In [6]:
a[2]

np.int64(9)

In [9]:
# 2 dimensional array

a = np.array([[1,2], [3,4], [5,6]])

a.ndim # ndim to print dimensions

2

In [8]:
a=np.array([5,6,9])
a.ndim

1

In [7]:
a=np.array([[1,2], [3,4], [5, 6]])
a.ndim

2

In [6]:
# to print the byte size of each of the properties. 
a.itemsize 

8

In [3]:
a.dtype

dtype('int64')

In [11]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [12]:
np.std(a)

np.float64(1.707825127659933)

In [15]:
# 2d array
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [16]:
a+b

array([[ 6,  8],
       [10, 12]])

In [17]:
a*b

array([[ 5, 12],
       [21, 32]])

In [18]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [19]:
a.dot(b)


array([[19, 22],
       [43, 50]])