<div style="text-align: center;">
    <h1>Iterate NumPy array using nditer</h1>
</div>

In [1]:
import numpy as np


In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [4]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for column in a:
    print(column)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
# flatten the list 
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


### `np.nditer` is a a powerful multi-dimensional iterator in NumPy, used to iterate efficiently over arrays of any shape and dimension.
### It gives you more control than basic Python `for` loops or `numpy.flat`. 

In [9]:
for x in np.nditer(a, order='C' ):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
# order {‘C’, ‘F’, ‘A’, ‘K’}, optional
# F means Fortran order
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


<img src="fortran_order.png"/>

In [16]:
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [18]:
# readwrite indicates the operand will be read from and written to.

for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*x

a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

In [ ]:
# iterate two arrays

b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [22]:
for x, y in np.nditer([a,b]):
    print(x, y)

0 3
1 3
16 3
81 3
256 7
625 7
1296 7
2401 7
4096 11
6561 11
10000 11
14641 11


For more, let's check out numpy.nditer documentation (https://numpy.org/doc/stable/reference/generated/numpy.nditer.html)